// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9JKiAFRd-xA1_t-MfEcWBNu6shyWXfqw',
    appId: '1:1069400504643:web:ffe5a75bdc16eba5f997f6',
    messagingSenderId: '1069400504643',
    projectId: 'haruto-0422',
    authDomain: 'haruto-0422.firebaseapp.com',
    storageBucket: 'haruto-0422.firebasestorage.app',
    measurementId: 'G-SRQR2Y9MXW',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9JKiAFRd-xA1_t-MfEcWBNu6shyWXfqw',
    appId: '1:1069400504643:web:ffe5a75bdc16eba5f997f6',
    messagingSenderId: '1069400504643',
    projectId: 'haruto-0422',
    authDomain: 'haruto-0422.firebaseapp.com',
    storageBucket: 'haruto-0422.firebasestorage.app',
    measurementId: 'G-SRQR2Y9MXW',
  );

}