name: sdjapp1

description: A new Flutter project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  firebase_core: ^4.8.0
  cloud_firestore: ^6.4.0

  http: ^1.6.0
  
  camera: ^0.11.2
  gallery_saver_plus: ^3.2.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1

  google_generative_ai: ^0.4.7

flutter:
  uses-material-design: true